# Generated by Django 3.1 on 2020-08-18 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '배송', 'verbose_name_plural': '배송'},
        ),
    ]
