# Generated by Django 3.1 on 2020-08-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='name',
            field=models.CharField(default=None, max_length=32, verbose_name='이름'),
        ),
    ]
